
# Site configuration

targets:
    - name:         "desktop"
      description:  "Desktop or tablet"

sites:
    - name:         "pivotx-backend"
      description:  "PivotX back-end"

languages:
    - name:         "nl"
      description:  "Dutch"
      locale:       "nl_NL.utf-8"

    - name:         "en"
      description:  "English"
      locale:       "en_GB.utf-8"


routeprefixes:
    - filter:       { target: "desktop", site: "pivotx-backend", language: "en" }
      prefix:       "|^(http://.+/pivotx/en/)|"
# @todo should not do regexes but something simpler?

routes:
    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      ""
      public:       ""
      defaults:     { _rewrite: "_page/dashboard" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_page/dashboard"
      public:       "dashboard"
      defaults:     { _controller: "BackendBundle:Backend:any", _view: "Core/dashboard.html.twig" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_page/login"
      public:       "login"
      defaults:     { _controller: "BackendBundle:Backend:showLogin" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_page/logout"
      public:       "logout"
      defaults:     { _controller: "BackendBundle:Backend:any", _view: "Core/logout.html.twig" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: "en" }
      pattern:      "_table/{entity}"
      public:       "table/{entity}"
      defaults:     { _controller: "BackendBundle:Crud:showTable", _role: "ROLE_EDITOR" }
      requirements:
          entity: "[A-Za-z_]+[A-Za-z0-9]+"

    - filter:       { target: "desktop", site: "pivotx-backend", language: "en" }
      pattern:      "_table/{entityref}/{id}/{entity}"
      public:       "table/{entityref}/{id}/{entity}"
      defaults:     { _controller: "BackendBundle:Crud:showSubTable", _role: "ROLE_EDITOR" }
      requirements:
          entity:    "[A-Za-z_]+[A-Za-z0-9_]+"
          entityref: "[A-Za-z_]+[A-Za-z0-9_]+"
          id:        "[0-9]+"

    - filter:       { target: "desktop", site: "pivotx-backend", language: "en" }
      pattern:      "_table/{entity}/{id}"
      public:       "table/{entity}/{id}"
      defaults:     { _controller: "BackendBundle:Crud:showRecord", _role: "ROLE_EDITOR" }
      requirements:
          entity:   "[A-Za-z_]+[A-Za-z0-9_]+"
          id:       "[0-9]+"

    - filter:       { target: "desktop", site: "pivotx-backend", language: "en" }
      pattern:      "_table/{entity}/suggest/{field}"
      public:       "table/{entity}/suggest/{field}"
      defaults:     { _controller: "BackendBundle:Crud:suggestFieldValue", _role: "ROLE_EDITOR" }
      requirements:
          entity:   "[A-Za-z_]+[A-Za-z0-9_]+"
          field:    "[A-Za-z_]+[A-Za-z0-9_]+"

    - filter:       { target: "desktop", site: "pivotx-backend", language: "en" }
      pattern:      "_api/fileupload"
      public:       "api/fileupload"
      defaults:     { _controller: "BackendBundle:Upload:processUpload", _role: "ROLE_EDITOR" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: "en" }
      pattern:      "_developer/routing"
      public:       "developer/routing"
      defaults:     { _controller: "BackendBundle:Developer:showRouting", _role: "ROLE_DEVELOPER" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: "en" }
      pattern:      "_developer/views"
      public:       "developer/views"
      defaults:     { _controller: "BackendBundle:Developer:showViews", _role: "ROLE_DEVELOPER" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: "en" }
      pattern:      "_developer/formats"
      public:       "developer/formats"
      defaults:     { _controller: "BackendBundle:Developer:showFormats", _role: "ROLE_DEVELOPER" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: "en" }
      pattern:      "_entities/all"
      public:       "entities/all"
      defaults:     { _controller: "BackendBundle:Entities:showEntities" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: "en" }
      pattern:      "_entity/{entity}"
      public:       "entity/{entity}"
      defaults:     { _controller: "BackendBundle:Entities:showEntity", _role: "ROLE_ADMIN" }
      requirements:
          entity:    "[A-Za-z_]+[A-Za-z0-9_]+"

    - filter:       { target: "desktop", site: "pivotx-backend", language: "en" }
      pattern:      "_entities/all/mutate"
      public:       "entities/all/mutate"
      defaults:     { _controller: "BackendBundle:Entities:showMutate", _role: "ROLE_ADMIN" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: "en" }
      pattern:      "_developer/site/new"
      public:       "site/new"
      defaults:     { _controller: "BackendBundle:Developer:showSite", _role: "ROLE_ADMIN" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_profile/home"
      public:       "profile/home"
      defaults:     { _controller: "BackendBundle:Backend:any", _view: "Core/dashboard.html.twig" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: "en" }
      pattern:      "_page/not-found"
      public:       "page-not-found"
      defaults:     { _nothing: "not-found" }
