
# Site configuration

targets:
    - name:         "desktop"
      description:  "Desktop or tablet"

sites:
    - name:         "pivotx-backend"
      description:  "PivotX back-end"

languages:
    - name:         "nl"
      description:  "Dutch"
      locale:       "nl_NL.utf-8"

    - name:         "en"
      description:  "English"
      locale:       "en_GB.utf-8"

    - name:         "none"
      description:  "Shared resources"
      locale:       ""


routeprefixes:
    - filter:       { target: "desktop", site: "pivotx-backend", language: "en" }
      prefix:       "http://%request.host%/pivotx/en/"

    - filter:       { target: "desktop", site: "pivotx-backend", language: "nl" }
      prefix:       "http://%request.host%/pivotx/nl/"

    - filter:       { target: false, site: "pivotx-backend", language: false }
      prefix:       "http://%request.host%/pivotx/"

routes:
    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_page/dashboard"
      public:       "dashboard"
      defaults:     { _controller: "BackendBundle:Backend:any", _view: "Core/dashboard.html.twig" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_page/login"
      public:       "login"
      defaults:     { _controller: "BackendBundle:Backend:showLogin" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_page/login_check"
      public:       "login_check"
      defaults:     { _controller: "BackendBundle:Backend:performLoginCheck" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_page/logout"
      public:       "logout"
      defaults:     { _controller: "BackendBundle:Backend:performLogout", _view: "Core/logout.html.twig" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_page/no_access"
      public:       "no-access"
      defaults:     { _controller: "BackendBundle:Backend:any", _view: "Core/no_access.html.twig" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_siteadmin/status"
      public:       "siteadmin/status"
      defaults:     { _controller: "BackendBundle:Siteadmin:showStatus", _role: "ROLE_EDITOR" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_siteadmin/clearcaches/{target}"
      public:       "siteadmin/clear-cache/{target}"
      defaults:     { _controller: "BackendBundle:Siteadmin:clearCaches", _role: "ROLE_EDITOR" }
      requirements:
          target:    "[a-z_]+"

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_siteadmin/rebuildwebresources"
      public:       "siteadmin/rebuild-webresources"
      defaults:     { _controller: "BackendBundle:Siteadmin:rebuildWebresources", _role: "ROLE_EDITOR" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_table/{entity}"
      public:       "table/{entity}"
      defaults:     { _controller: "BackendBundle:Crud:showTable", _role: "ROLE_EDITOR" }
      requirements:
          entity: "[A-Za-z_]+[A-Za-z0-9]+"

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_table/{entityref}/{id}/{entity}"
      public:       "table/{entityref}/{id}/{entity}"
      defaults:     { _controller: "BackendBundle:Crud:showSubTable", _role: "ROLE_EDITOR" }
      requirements:
          entity:    "[A-Za-z_]+[A-Za-z0-9_]+"
          entityref: "[A-Za-z_]+[A-Za-z0-9_]+"
          id:        "[0-9]+"

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_table/{entity}/{id}"
      public:       "table/{entity}/{id}"
      defaults:     { _controller: "BackendBundle:Crud:showRecord", _role: "ROLE_EDITOR" }
      requirements:
          entity:   "[A-Za-z_]+[A-Za-z0-9_]+"
          id:       "[0-9]+"

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_table/{entity}/suggest/{field}"
      public:       "table/{entity}/suggest/{field}"
      defaults:     { _controller: "BackendBundle:Crud:suggestFieldValue", _role: "ROLE_EDITOR" }
      requirements:
          entity:   "[A-Za-z_]+[A-Za-z0-9_]+"
          field:    "[A-Za-z_]+[A-Za-z0-9_]+"

    - filter:       { target: false, site: "pivotx-backend", language: false }
      pattern:      "_backend/fileupload"
      public:       "backend/fileupload"
      defaults:     { _controller: "BackendBundle:Upload:processUpload", _role: "ROLE_EDITOR" }

    - filter:       { target: false, site: "pivotx-backend", language: false }
      pattern:      "_backend/fileembed/{name}"
      public:       "backend/fileembed/{name}"
      defaults:     { _controller: "BackendBundle:Upload:getTemporaryEmbed", _role: "ROLE_EDITOR" }
      requirements:
          name:     "[0-9a-f-]+"

    - filter:       { target: false, site: "pivotx-backend", language: false }
      pattern:      "_backend/filetempdownload/{name}"
      public:       "backend/filetempdownload/{name}"
      defaults:     { _controller: "BackendBundle:Upload:getTemporaryFileDownload", _role: "ROLE_EDITOR" }
      requirements:
          name:     "[0-9a-f.-]+"

    - filter:       { target: false, site: "pivotx-backend", language: false }
      pattern:      "_backend/resourceselection/{id}"
      public:       "backend/resourceselection/{id}"
      defaults:     { _controller: "BackendBundle:Crud:getResourceInfo", _role: "ROLE_EDITOR" }
      requirements:
          id:       "[0-9]+"

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_developer/routing"
      public:       "developer/routing"
      defaults:     { _controller: "BackendBundle:Developer:showRouting", _role: "ROLE_DEVELOPER" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_developer/views"
      public:       "developer/views"
      defaults:     { _controller: "BackendBundle:Developer:showViews", _role: "ROLE_DEVELOPER" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_developer/formats"
      public:       "developer/formats"
      defaults:     { _controller: "BackendBundle:Developer:showFormats", _role: "ROLE_DEVELOPER" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_entities/all"
      public:       "entities/all"
      defaults:     { _controller: "BackendBundle:Entities:showEntities" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_entity/{entity}"
      public:       "entity/{entity}"
      defaults:     { _controller: "BackendBundle:Entities:showEntity", _role: "ROLE_ADMIN" }
      requirements:
          entity:    "[A-Za-z_]+[A-Za-z0-9_]+"

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_entities/all/mutate"
      public:       "entities/all/mutate"
      defaults:     { _controller: "BackendBundle:Entities:showMutate", _role: "ROLE_ADMIN" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_developer/site/new"
      public:       "site/new"
      defaults:     { _controller: "BackendBundle:Developer:showSite", _role: "ROLE_ADMIN" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_developer/site/mutate"
      public:       "site/mutate"
      defaults:     { _controller: "BackendBundle:Developer:mutateSite", _role: "ROLE_ADMIN" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_developer/site/load"
      public:       "site/load"
      defaults:     { _controller: "BackendBundle:Developer:loadSite", _role: "ROLE_ADMIN" }

    - filter:       { target: false, site: "pivotx-backend", language: false }
      pattern:      "_documentation/{name}"
      public:       "documentation/{name}"
      defaults:     { _controller: "BackendBundle:Backend:showDocumentation", _view: "Documentation/page.html.twig", _role: "ROLE_EDITOR" }
      requirements:
          name:      "[A-Za-z0-9_]+"

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_profile/home"
      public:       "profile/home"
      defaults:     { _controller: "BackendBundle:Backend:any", _view: "Developer/profile.html.twig" }

    - filter:       { target: false, site: "pivotx-backend", language: "none" }
      pattern:      "_cwr/{file}"
      public:       "cwr/{file}"
      defaults:     { _controller: "CoreBundle:Cwr:cwr" }
      requirements:
          file:     "[A-Za-z0-9/_.-]+[.][A-Za-z0-9]+"

    - filter:       { target: false, site: "pivotx-backend", language: false }
      pattern:      "_page/login-redirect"
      public:       ""
      defaults:     { _redirect: "(l=en)@_page/dashboard" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_http/404"
      public:       "page-not-found"
      defaults:     { _nothing: "not-found" }
