
# Site configuration

targets:
    - name:         "desktop"
      description:  "Desktop or tablet"

sites:
    - name:         "pivotx-backend"
      description:  "PivotX back-end"

languages:
    - name:         "nld"
      description:  "Dutch"
      locale:       "nl_NL.utf-8"

    - name:         "eng"
      description:  "English"
      locale:       "en_GB.utf-8"


routeprefixes:
    - filter:       { target: "desktop", site: "pivotx-backend", language: "eng" }
      prefix:       "|^(http://.+/pivotx/en/)|"
# @todo should not do regexes but something simpler?

routes:
    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      ""
      public:       ""
      defaults:     { _rewrite: "_page/dashboard" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_page/dashboard"
      public:       "dashboard"
      defaults:     { _controller: "BackendBundle:Backend:any", _view: "BackendBundle:Core:dashboard.html.twig" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_page/login"
      public:       "login"
      defaults:     { _controller: "BackendBundle:Backend:showLogin" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: false }
      pattern:      "_page/logout"
      public:       "logout"
      defaults:     { _controller: "BackendBundle:Backend:any", _view: "BackendBundle:Core:logout.html.twig" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: "eng" }
      pattern:      "_table/{entity}"
      public:       "table/{entity}"
      defaults:     { _controller: "BackendBundle:Crud:showTable" }
      requirements:
          entity: "[A-Za-z_]+[A-Za-z0-9]+"

    - filter:       { target: "desktop", site: "pivotx-backend", language: "eng" }
      pattern:      "_table/{entityref}/{id}/{entity}"
      public:       "table/{entityref}/{id}/{entity}"
      defaults:     { _controller: "BackendBundle:Crud:showSubTable" }
      requirements:
          entity:    "[A-Za-z_]+[A-Za-z0-9_]+"
          entityref: "[A-Za-z_]+[A-Za-z0-9_]+"
          id:        "[0-9]+"

    - filter:       { target: "desktop", site: "pivotx-backend", language: "eng" }
      pattern:      "_table/{entity}/{id}"
      public:       "table/{entity}/{id}"
      defaults:     { _controller: "BackendBundle:Crud:showRecord" }
      requirements:
          entity:   "[A-Za-z_]+[A-Za-z0-9_]+"
          id:       "[0-9]+"

    - filter:       { target: "desktop", site: "pivotx-backend", language: "eng" }
      pattern:      "_table/{entity}/suggest/{field}"
      public:       "table/{entity}/suggest/{field}"
      defaults:     { _controller: "BackendBundle:Crud:suggestFieldValue" }
      requirements:
          entity:   "[A-Za-z_]+[A-Za-z0-9_]+"
          field:    "[A-Za-z_]+[A-Za-z0-9_]+"

    - filter:       { target: "desktop", site: "pivotx-backend", language: "eng" }
      pattern:      "_api/fileupload"
      public:       "api/fileupload"
      defaults:     { _controller: "BackendBundle:Upload:processUpload" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: "eng" }
      pattern:      "_developer/routing"
      public:       "developer/routing"
      defaults:     { _controller: "BackendBundle:Developer:showRouting" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: "eng" }
      pattern:      "_developer/views"
      public:       "developer/views"
      defaults:     { _controller: "BackendBundle:Developer:showViews" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: "eng" }
      pattern:      "_developer/formats"
      public:       "developer/formats"
      defaults:     { _controller: "BackendBundle:Developer:showFormats" }

    - filter:       { target: "desktop", site: "pivotx-backend", language: "eng" }
      pattern:      "_page/not-found"
      public:       "page-not-found"
      defaults:     { _nothing: "not-found" }
